# Generated by Django 6.0.4 on 2026-07-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercuryMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32)),
                ('account_id', models.CharField(max_length=32)),
                ('service_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('service_start_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MercurySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('ocp_key', models.CharField(max_length=32)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mercury.mercurymeter')),
            ],
        ),
    ]
