# Generated by Django 5.1.6 on 2025-03-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('applied_date', models.DateField()),
                ('daily_fixed_price', models.FloatField(help_text='Unit: New Zealand cent')),
                ('GST_ratio', models.FloatField(default=0.15)),
                ('levy', models.FloatField(help_text='Unit: New Zealand cent')),
                ('default_unit_price', models.FloatField(help_text='The unit price of "all other time". It means the time period which is not mentioned by any of linked Price records. Unit: New Zealand cent')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Time period name that this price applies on, e.g. peak, off-peak, daytime, night, weekdays, weekend.', max_length=32)),
                ('unit_price', models.FloatField(help_text='Unit: New Zealand cent')),
                ('Monday', models.BooleanField(default=False)),
                ('Tuesday', models.BooleanField(default=False)),
                ('Wednesday', models.BooleanField(default=False)),
                ('Thursday', models.BooleanField(default=False)),
                ('Friday', models.BooleanField(default=False)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.chargingplan')),
            ],
        ),
    ]
