# Generated by Django 5.1.6 on 2025-03-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingplan',
            name='daily_fixed_price',
            field=models.FloatField(help_text='Exclude GST. Unit: New Zealand cent'),
        ),
        migrations.AlterField(
            model_name='chargingplan',
            name='default_unit_price',
            field=models.FloatField(help_text='The unit price in other time. It excludes the time when special prices are applied. Exclude GST.  Unit: New Zealand cent'),
        ),
        migrations.AlterField(
            model_name='chargingplan',
            name='levy',
            field=models.FloatField(help_text='Exclude GST. Unit: New Zealand cent'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time_from',
            field=models.TimeField(help_text='In format of HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time_to',
            field=models.TimeField(help_text='In format of HH:MM:SS. If ends at midnight, input 23:59:59. If lasts to next day, create another record that time_from = 00:00:00 (remember days of week +1).'),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_price',
            field=models.FloatField(help_text='Exclude GST. Unit: New Zealand cent'),
        ),
    ]
