# Generated by Django 6.0.4 on 2026-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_alter_chargingplan_daily_fixed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingplan',
            name='applied_date',
            field=models.DateField(help_text='Optional.', null=True),
        ),
        migrations.AlterField(
            model_name='chargingplan',
            name='default_unit_price',
            field=models.FloatField(help_text='The unit price in other time. It excludes the time when special prices are applied. Exclude GST.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time_to',
            field=models.TimeField(help_text='In format of HH:MM:SS. If end time is smaller than start time, it means the next day.'),
        ),
    ]
