# Generated by Django 6.0.4 on 2026-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0003_alter_chargingplan_applied_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingplan',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
