# Generated by Django 6.0.4 on 2026-07-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0004_alter_chargingplan_applied_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingplan',
            name='applied_date',
        ),
    ]
