# Generated by Django 5.1.6 on 2025-03-01 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnergyMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=32)),
                ('contract_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField()),
                ('fetched_days', models.IntegerField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactEnergy.contactenergymeter')),
            ],
        ),
    ]
