# Generated by Django 5.1.6 on 2025-03-01 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactEnergy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnergySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_date', models.DateField()),
                ('auth', models.CharField(max_length=200)),
                ('csrf_token', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContactEnergy.contactenergymeter')),
            ],
        ),
        migrations.DeleteModel(
            name='GetData',
        ),
    ]
