# Generated by Django 5.1.6 on 2025-03-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactEnergy', '0002_contactenergysession_delete_getdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenergysession',
            name='current_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contactenergysession',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contactenergysession',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
