# Generated by Django 5.1.6 on 2025-03-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactEnergy', '0003_alter_contactenergysession_current_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenergysession',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='contactenergysession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contactenergysession',
            name='start_date',
        ),
        migrations.AddField(
            model_name='contactenergysession',
            name='finished_dates',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contactenergysession',
            name='total_dates',
            field=models.SmallIntegerField(null=True),
        ),
    ]
