# Generated by Django 5.1.6 on 2025-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactEnergy', '0004_remove_contactenergysession_current_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenergysession',
            name='failed_dates',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactenergysession',
            name='finished_dates',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contactenergysession',
            name='total_dates',
            field=models.SmallIntegerField(default=0),
        ),
    ]
