# Generated by Django 5.1.6 on 2025-03-01 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.PositiveIntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('hour', models.SmallIntegerField()),
                ('value', models.FloatField(verbose_name='Electricity usage amount (kWh)')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meter.meter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('provider', 'meter_id'), name='unique_meter'),
        ),
    ]
