# Generated by Django 5.1.6 on 2025-03-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='day',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='month',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='year',
        ),
        migrations.AddField(
            model_name='usage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
