# Generated by Django 5.1.6 on 2025-03-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0002_remove_usage_day_remove_usage_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='date',
            field=models.DateField(),
        ),
    ]
