# Generated by Django 5.1.6 on 2025-03-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0003_alter_usage_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
