# Generated by Django 5.1.6 on 2025-03-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0004_delete_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateTimeField()),
                ('value', models.FloatField(null=True, verbose_name='Electricity usage amount (kWh)')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meter.meter')),
            ],
        ),
    ]
