# Generated by Django 5.1.6 on 2025-03-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0005_usage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usage',
            constraint=models.UniqueConstraint(fields=('meter', 'time_slot'), name='unique_usage'),
        ),
    ]
