# Generated by Django 6.0.1 on 2026-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0006_usage_unique_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
