# Generated by Django 6.0.1 on 2026-07-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meter', '0007_meter_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
